---
ansible:
  # Add the name of used custom Ansible modules. Otherwise ansible-later
  # can't detect unknown modules and will through an error.
  # Modules which are bundled with the role and placed in a './library'
  # directory will be auto-detected and don't need to be added to this list.
  custom_modules: []

  # List of yamllint compatible literal bools (ANSIBLE0014)
  literal-bools:
    - "true"
    - "false"
rules:
  exclude_files:
    - molecule/
    - requirements.txt
...
