---
- name: Converge
  hosts: all
  vars:
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: "Include {{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_name }}"

...
